//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblÜrün
    {
        public int ÜrünId { get; set; }
        public string ÜrünAd { get; set; }
        public Nullable<double> ÜrünFiyat { get; set; }
        public string ÜrünResmi { get; set; }
        public int KategoriId { get; set; }
    }
}
